window.noname_update = {
	version: "1.5.0",
	update: "1.5.0",
	changeLog: [
		"优化圣仲裁者天平技能描述",
		"优化魔弓魔眼ai",
		"修复原初之弓流星圣弹无法移除治疗bug",
		"调整传教士神的门徒代码",
		"优化和修复虚弱代码",
		"优化三版女武神英灵召唤选牌代码",
		"修复传教士神的门徒错误技能id",
		"优化禁断之力发动时提示",
		"修复真龙女王龙神恩惠偶尔会触发两次的问题",
		"增加可见手牌显示",
		"优化手机技能发动弹窗显示以容纳更多内容",
		"完成BOSS模式",
		"优化房间名设置，显示是否多控",
		"增加get.countTongMingPai/countYiMingPai函数",
		"修复在深色模式下独立显示能量和红蓝专属数字颜色不正常",
		"修复gain事件处理give/giveAuto错误动画处理，使visibleMove按字面意思使用",
		"增加DIY势力",
		"完善get.shiQiMax/zhanJiMax函数",
		"调整game.versusHoverHandcards函数位置",
		"intro中content新增zhiShiWu字符串可用，同mark",
		"增加player:getZhiShiWuLimit函数，输入参数为zhiShiWu名；指示物max设置支持函数，输入参数为player ",
		"房间名多控前缀变为全局判断，不只是星杯模式",
		"增加game:addPlayerOL/removePlayerOL函数",
		"是图鉴模式正常显示boss角色",
		"角色包选项中增加disable,用于禁止角色被启用",
		"优化discard事件弃置盖牌获取翻译的过程，优先使用intro中的name",
		"修复星杯模式切换顺位会导致队伍顺序错乱",
		"增加星杯模式联机多控情况右上角手牌按钮显示，该按钮用于聚合显示队友手牌",
		"增加get.shiQiMax和get.zhanJiMaxi函数，输入参数为side,若无side则为全局默认上限",
		"gongJiWeiMingZhong触发器增加cause和causeCard属性",
	],
	files: [

	],
};
